project:
  type: website
  render:
    - 404.qmd
    - index.qmd
    - general/*.qmd
    - part-01/*.qmd
    - part-02/*.qmd
    - part-03/*.qmd
    - part-04/*.qmd
    - part-05/*.qmd
    - part-06/*.qmd
    - part-07/*.qmd
    # - part-08/*.qmd
    # - part-09/*.qmd
    # - part-10/*.qmd
    # - part-11/*.qmd
    # - part-12/*.qmd
    # - part-13/*.qmd
website:
  title: "Energy System Optimization with Julia"
  repo-url: https://github.com/TobiasCors/Energy-System-Optimization
  repo-actions: [edit, source, issue]
  site-url: https://TobiasCors.github.io/Energy-System-Optimization
  bread-crumbs: true
  sidebar:
    style: floating
    logo: https://images.unsplash.com/photo-1617228679684-890412dc57a5?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
    collapse-level: 1 
    search: true
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Syllabus"
        href: general/syllabus.qmd
      - text: "***"
      - text: "01 Introduction"
        href: part-01/lecture-introduction.qmd
      - section: "02 First Steps"
        contents:
          - text: "Lecture"
            href: part-02/lecture-firststeps.qmd
          - text: "01 - Variables"
            href: part-02/tutorial-02-01-variables.qmd
          - text: "02 - Vectors"
            href: part-02/tutorial-02-02-vectors.qmd
          - text: "03 - Comparisons"
            href: part-02/tutorial-02-03-comparisons.qmd
          - text: "04 - Loops"
            href: part-02/tutorial-02-04-loops.qmd
          - text: "05 - Dictionaries"
            href: part-02/tutorial-02-05-dicts.qmd
      - section: "03 Data"
        contents:
          - text: "Lecture"
            href: part-03/lecture-packages.qmd
          - text: "01 - Functions"
            href: part-03/tutorial-03-01-functions.qmd
          - text: "02 - Packages"
            href: part-03/tutorial-03-02-handling.qmd
          - text: "03 - DataFrames"
            href: part-03/tutorial-03-03-DataFrames.qmd
          - text: "04 - Input and Output"
            href: part-03/tutorial-03-04-IO.qmd
          - text: "05 - Plotting"
            href: part-03/tutorial-03-05-Plotting.qmd
      - section: "04 Optimization"
        contents:
          - text: "Lecture"
            href: part-04/lecture-jump.qmd
          - text: "01 - JuMP"
            href: part-04/tutorial-04-01-jump.qmd
          - text: "02 - Bounds"
            href: part-04/tutorial-04-02-bounds.qmd
          - text: "03 - Constraints"
            href: part-04/tutorial-04-03-constraints.qmd
          - text: "04 - Advanced"
            href: part-04/tutorial-04-04-advanced.qmd
          - text: "05 - Transport"
            href: part-04/tutorial-04-05-transport.qmd
      - section: "05 Dispatch"
        contents:
          - text: "Lecture"
            href: part-05/lecture-dispatch.qmd
          - text: "Tutorial"
            href: part-05/tutorial-dispatch.qmd
      - section: "06 Commitment"
        contents:
          - text: "Lecture"
            href: part-06/lecture-commitment.qmd
          - text: "Tutorial"
            href: part-06/tutorial-commitment.qmd
      - section: "07 Storage"
        contents:
          - text: "Lecture"
            href: part-07/lecture-storage.qmd
          - text: "Tutorial"
            href: part-07/tutorial-storage.qmd
      - section: "08 Design"
        contents:
          - text: "Lecture"
            href: part-08/lecture-design.qmd
      #     - text: "Tutorial"
      #       href: part-08/tutorial-districting.qmd
      # - section: "09 Safety"
      #   contents:
      #     - text: "Lecture"
      #       href: part-09/lecture-safety.qmd
      #     - text: "Tutorial"
      #       href: part-09/tutorial-safety.qmd
      # - section: "10 Intermission"
      #   contents:
      #     - text: "Lecture"
      #       href: part-10/lecture-intermission.qmd
      #     - text: "Tutorial"
      #       href: part-10/tutorial-intermission.qmd
      # - section: "11 Distancing"
      #   contents:
      #     - text: "Lecture"
      #       href: part-11/lecture-distancing.qmd
      #     - text: "Tutorial"
      #       href: part-11/tutorial-distancing.qmd
      # - section: "12 Metro"
      #   contents:
      #     - text: "Lecture"
      #       href: part-12/lecture-rail.qmd
      #     - text: "Tutorial"
      #       href: part-12/tutorial-rail.qmd
      # - section: "13 Recap"
      #   contents:
      #     - text: "Lecture"
      #       href: part-13/lecture-recap.qmd
      #     - text: "Tutorial"
      #       href: part-13/tutorial-recap.qmd
      - text: "***"
      - section: "Cheatsheets"
        contents:
          - text: "Julia"
            href: general/cheatsheet-julia.qmd
          - text: "JuMP"
            href: general/cheatsheet-jump.qmd
      - text: "FAQs"
        href: general/faq.qmd
      - text: "Literature"
        href: general/literature.qmd

  page-footer: 
    center: "Energy System Optimization with Julia, Tobias Cors</br>CC BY-NC-SA 4.0" 
    right: 
      - icon: github
        href: https://github.com/TobiasCors/Energy-System-Optimization
      - icon: linkedin
        href: https://linkedin.com/in/tobias-cors

format:
  html:
    theme: [litera, styles.scss]
    toc: true
    highlight-style: arrow
    linkcolor: "#a60000"
    code-copy: true
    code-link: true
    toc-location: right
    code-overflow: wrap
    code-block-bg: true
    code-block-border-left: "#AD1F00"
    include-in-header:
      - general/header.html

  pdf:
    documentclass: report
    geometry:
        - margin=1in
    fontfamily: roboto
    fontfamilyoptions: sfdefault
    colorlinks: true
    include-in-header: 
      text: |
        \usepackage{unicode-math}
        \usepackage{listings}
        \usepackage{xcolor}
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
execute:
  freeze: auto


