---
title: "Syllabus"
subtitle: "This years course structure"

html:
    theme: [default, ../styles.scss]
    highlight-style: breezedark
    linkcolor: "#a60000"
    code-copy: true
    code-link: true
    toc: true
---
# Part I 
## Introduction to Julia and Modelling

In the first part, an introduction to the basic concepts of programming in Julia and to mathematical modelling is provided. Students will learn the Julia syntax, data types, as well as how to implement loops and functions in Julia. We will introduce core Julia libraries, too, including JuMP and DataFrames. Once these concepts are understood, we will learn how they can be used to solve problems.

## Lectures

**Welcome and Introduction (I)**\
Introduction to the course and mathematical modelling

**First Steps in Julia (II)**\
Vectors, matrices, basic operations loops and functions

**Packages and Data Management (III)**\
Package Management, DataFrames, reading and writing data

**Modelling with JuMP (IV)**\
Modeling with JuMP with variables, parameters and constraints

# Part II 
## Applied Optimization with Basic Models

In the second part, we will cover energy system optimization based on basic modelling concepts. We will start with the classic generator expansion problem and learn how to model and solve it using JuMP. Afterwards we start to bring together further modelling concepts, such as the unit commitment and storages, to build a digital twin of a power system for various decision problems. Finally, we developed a basic framework to model and solve operations and investment planning problems of energy systems.

## Lectures

**Generator Expansion Planning (V)**\
A case study on generator expansion planning

**Unit Commitment as Short-term Scheduling (VI)**\
A case study on unit commitment as short-term scheduling

**Storages (VII)**\
A case study on storages

**Investment Planning (VIII)**\
A case study on investment planning

# Part III 
## Applied Optimization with Advanced Models

In the third part, we will cover more advanced optimization models and concepts. We will start to extend the basic models to more complex models, such as multi-energy systems and uncertainty modelling.

## Lectures

**Multi-energy Systems (IX)**\
A case study on multi-energy systems

**Uncertainty Modelling and Renewable Energy Integration (X)**\
A case study on uncertainty modelling and renewable energy integration

**Intermission: Exam Preparation (XI)**\
We will prepare for the exam by solving a set of exercises together in the lecture.

**Electricity Market and Carbon Pricing (XII)**\
A case study on electricity market and carbon pricing

**Recap and Discussion (XIII)**\
We repeat the concepts from the course and discuss all your remaining questions