on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # - name: Print working directory
      #   run: pwd

      # - name: List files in current directory
      #   run: ls -la

      # - name: List files in parent directory
      #   run: ls -la ..

      # - name: List files in grandparent directory
      #   run: ls -la ../..

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'  # Specify the Julia version you need

      - name: Install Python and Jupyter
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install jupyter

      - name: Install IJulia and Rebuild
        run: |
          julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.build("IJulia")'

      - name: List Jupyter Kernels
        run: jupyter kernelspec list

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      # - name: Install TinyTeX
      #   run: |
      #     quarto install tinytex
      #     export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH
      #     sudo chmod -R a+rx $HOME/.TinyTeX # Fix permissions if necessary
      #     if ! command -v tlmgr &> /dev/null; then
      #       echo "TinyTeX installation failed or tlmgr is not in PATH"
      #       exit 1
      #     fi
      
      # - name: Verify TinyTeX Installation
      #   run: |
      #     export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH # Ensure PATH is updated
      #     if ! command -v tlmgr &> /dev/null; then
      #       echo "tlmgr could not be found"
      #       exit 1
      #     fi
      #     tlmgr --version

      # - name: Update LaTeX Packages
      #   run: |
      #     export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH # Ensure PATH is updated
      #     if ! command -v tlmgr &> /dev/null; then
      #       echo "tlmgr could not be found"
      #       exit 1
      #     fi
      #     tlmgr update --self
      #     tlmgr update --all
      #     tlmgr install collection-latexrecommended collection-fontsrecommended collection-latexextra
    
      # New TeX Live step
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full
      
      - name: Install rsvg-convert
        run: sudo apt-get install -y librsvg2-bin
  
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Debug Logs
      #   run: cat general/cheatsheet-julia.log

      # - name: Upload cheatsheet log
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cheatsheet-julia-log
      #     path: general/cheatsheet-julia.log